= date4j

== What?

This is Ian Darwin's repackaging of Hirondelle Systems's Date4J API.

Think of *date4j* as "the small, simple, *sensible* Date API for Java."

Another take: "One class to date them all". Literally, one class for almost everything.

*Read* all about it on http://date4j.net/

*But* do note that the problems that lead to the creation of _date4j_ have been solved in the current release of Java!
The Java 8 "new date/time API" (JSR-310, _java.time_) has what you need; see https://docs.oracle.com/javase/tutorial/datetime/

*Find* link:$$http://search.maven.org/#search|ga|1|a%3A%22hirondelle-date4j%22$$[the current version in Maven Central for use in Maven, Gradle, Buildr, Ivy, Grape, etc.]
Note that the Maven package is _hirondelle-date4j_.

.*Build*
image:http://img.shields.io/badge/license-BSD2-green.svg[link="http://github.com/IanDarwin/date4j"]
image:https://maven-badges.herokuapp.com/maven-central/com.darwinsys/hirondelle-date4j/badge.svg[
	link="https://maven-badges.herokuapp.com/maven-central/com.darwinsys/hirondelle-date4j"]

Remember, today one might just as well use +java.time.*+ instead.

== Mavenizing Date4J

The code's original author is not a fan of Maven, but he thoughtfully put it
under the BSD license, and his web page links to my redistribution, this is my
"Redistribution and use in source and binary forms" with an intent to make
it available to all Maven/Gradle/Buildr/etc Nexus/MavenCentral users.

I originally said that:
_I have made no code changes, and plan to make none._
However, that is no longer strictly true; since the original author
has not updated his code in five years, I've taken it upon myself
to add a _module-info_ file, just declaring the package itself.
There are no external dependencies, so that's valid.
This should help those wanting to use date4j with JPMS, JigSaw, 
the Java Modules System, whatever you call Java Modules.

I have however reorganized the code into standard Maven/Gradle directory
structure, added the POM file, removed the lib directory's only file
JUnit.jar (replaced with a Maven depends), and set this up for inclusion in
Maven Central and uploaded it (URL above).
